/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bancodados;

import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author Tomás Abril
 */
public class Janela extends javax.swing.JFrame {

    public ArrayList<LivroTO> listaLivro;
    public LivroDAO livroDAO;
    int indice;
    ImageIcon icone;

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
        indice = 0;
        livroDAO = new LivroDAO();
        listaLivro = livroDAO.listAll();
        updateTable();

    }

    private int updateTable() {

        jTable1.setValueAt(Integer.toString(listaLivro.get(indice).getLivro_id()), 0, 0);
        jTable1.setValueAt(listaLivro.get(indice).getTitulo(), 0, 1);
        jTable1.setValueAt(listaLivro.get(indice).getAutor(), 0, 2);
        jTable1.setValueAt(listaLivro.get(indice).getEditora(), 0, 3);
        jTable1.setValueAt(Integer.toString(listaLivro.get(indice).getAno()), 0, 4);
        jTable1.setValueAt(Integer.toString(listaLivro.get(indice).getGenero_id()), 0, 5);
        jTable1.setValueAt(listaLivro.get(indice).getDescricao(), 0, 6);
        jTable1.setValueAt(Double.toString(listaLivro.get(indice).getPreco()), 0, 7);
        jTable1.setValueAt(Integer.toString(listaLivro.get(indice).getEstoque()), 0, 8);
        jTable1.setValueAt(Integer.toString(listaLivro.get(indice).getReserva()), 0, 9);
        //esta retornando nulo?
        //icone = new ImageIcon(livroDAO.getCapaImage(listaLivro.get(indice).getLivro_id()));
        //jLabelImg.setIcon( icone );
        
        return 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ultimo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        anterior = new javax.swing.JButton();
        proximo = new javax.swing.JButton();
        primeiro = new javax.swing.JButton();
        textoBusca = new javax.swing.JTextField();
        busca = new javax.swing.JButton();
        jLabelImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ultimo.setText("Ultimo");
        ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultimoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "LIVRO_ID", "TITULO", "AUTOR", "EDITORA", "ANO", "GENERO", "DESCRICAO", "PRECO", "ESTOQUE", "RESERVA"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        anterior.setText("Anterior");
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });

        proximo.setText("Proximo");
        proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoActionPerformed(evt);
            }
        });

        primeiro.setText("Primeiro");
        primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeiroActionPerformed(evt);
            }
        });

        busca.setText("Busca");
        busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaActionPerformed(evt);
            }
        });

        jLabelImg.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabelImgComponentShown(evt);
            }
        });
        jLabelImg.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jLabelImgComponentAdded(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(busca)
                            .addComponent(textoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(primeiro)
                                .addGap(18, 18, 18)
                                .addComponent(anterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(proximo)
                                .addGap(18, 18, 18)
                                .addComponent(ultimo)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(primeiro)
                    .addComponent(anterior)
                    .addComponent(proximo)
                    .addComponent(ultimo))
                .addGap(18, 18, 18)
                .addComponent(textoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(busca)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultimoActionPerformed
        // TODO add your handling code here:
        indice = (listaLivro.size() - 1);
        updateTable();
    }//GEN-LAST:event_ultimoActionPerformed

    private void proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoActionPerformed
        // TODO add your handling code here:
        if (indice < (listaLivro.size() - 1)) {
            indice++;
        }
        updateTable();

    }//GEN-LAST:event_proximoActionPerformed

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        // TODO add your handling code here:
        if (indice > 0) {
            indice--;
        }
        updateTable();
    }//GEN-LAST:event_anteriorActionPerformed

    private void primeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeiroActionPerformed
        // TODO add your handling code here:
        indice = 0;
        updateTable();
    }//GEN-LAST:event_primeiroActionPerformed

    private void buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaActionPerformed
        // TODO add your handling code here:
        LivroTO tmp;
        tmp = livroDAO.find(textoBusca.getText());
        try {
            int tmpIndex = 0;
            for (LivroTO livro : listaLivro) {
                if (tmp.getLivro_id() == livro.getLivro_id()) {
                    indice = tmpIndex;
                    break;
                }
                tmpIndex++;
            }

            updateTable();

        } catch (Exception e1) {
            System.out.println("erro na busca: " + e1);
        }
    }//GEN-LAST:event_buscaActionPerformed

    private void jLabelImgComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabelImgComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelImgComponentShown

    private void jLabelImgComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jLabelImgComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelImgComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anterior;
    private javax.swing.JButton busca;
    private javax.swing.JLabel jLabelImg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton primeiro;
    private javax.swing.JButton proximo;
    private javax.swing.JTextField textoBusca;
    private javax.swing.JButton ultimo;
    // End of variables declaration//GEN-END:variables
}
